AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline container project ServiceCatalog product. (fdp-1p4dlgcoi)
Parameters:
  PortfolioProvider:
    Type: String
    Description: Provider Name
  LaunchConstraintARN:
    Type: String
    Description: ARN of the launch constraint role for ECS products.
  PortfolioId:
    Type: String
    Description: The SC portfolio this product will be attached to.
  RepoRootURL:
    Type: String
    Description: Root url for the repo containing the product templates.
  ProductVersionName:
    Type: String
    Description: The product version name in the service catalog
Resources:
  WebserverProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Container Codepipeline project
      Description: This product builds a codepipeline project for container CI/CD.
      Owner: !Ref 'PortfolioProvider'
      Distributor: !Ref 'PortfolioProvider'
      SupportDescription: Operations Team
      SupportEmail: support@yourcompany.com
      AcceptLanguage: en
      SupportUrl: http://helpdesk.yourcompany.com
      ProvisioningArtifactParameters:
        - Description: CodePipeline project
          Info:
            LoadTemplateFromURL: !Sub '${RepoRootURL}ecs/container-codepipeline-ra.yaml'
          Name: !Ref 'ProductVersionName'
  Associatenginxcf:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref 'PortfolioId'
      ProductId: !Ref 'WebserverProduct'
  constraintnginxcf:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    DependsOn: Associatenginxcf
    Properties:
      PortfolioId: !Ref 'PortfolioId'
      ProductId: !Ref 'WebserverProduct'
      RoleArn: !Ref 'LaunchConstraintARN'
      Description: !Ref 'LaunchConstraintARN'
Outputs:
  ProductId:
    Value: !Ref 'WebserverProduct'
