AWSTemplateFormatVersion: '2010-09-09'
Description: Linux EC2 Demo Webserver ServiceCatalog product. (fdp-1p4dlgcoi)
Parameters:
  PortfolioProvider:
    Type: String
    Description: Provider Name
  LaunchConstraintARN:
    Type: String
    Description: ARN of the launch constraint role for EC2 products.
  PortfolioId:
    Type: String
    Description: The SC portfolio this product will be attached to.
  RepoRootURL:
    Type: String
    Description: Root url for the repo containing the product templates.
  ProductVersionName:
    Type: String
    Description: The product version name in the service catalog
Resources:
  WebserverProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002
    Properties:
      Name: Demo Linux Webserver
      Description: This product builds a webserver (Apache or NGINX) EC2 instance.
      Owner: !Ref 'PortfolioProvider'
      Distributor: !Ref 'PortfolioProvider'
      ProvisioningArtifactParameters:
        - Description: NGINX webserver
          Info:
            LoadTemplateFromURL: !Sub '${RepoRootURL}ec2/sc-ec2-linux-nginx-nokey.yaml'
          Name: !Sub 'NGINX ${ProductVersionName}'
        - Description: Apache webserver
          Info:
            LoadTemplateFromURL: !Sub '${RepoRootURL}ec2/sc-ec2-linux-apache-nokey.yaml'
          Name: !Sub 'Apache ${ProductVersionName}'
      'Fn::Transform':
        Name: 'AWS::Include'
        Parameters:
          Location : "s3://CloudformationSnippetsBucket/scipoolprod-sc-lib-infra/support.yaml"
  Associatenginxcf:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref 'PortfolioId'
      ProductId: !Ref 'WebserverProduct'
  constraintnginxcf:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    DependsOn: Associatenginxcf
    Properties:
      PortfolioId: !Ref 'PortfolioId'
      ProductId: !Ref 'WebserverProduct'
      RoleArn: !Ref 'LaunchConstraintARN'
      Description: !Ref 'LaunchConstraintARN'
  TagOptionsTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '${RepoRootURL}ec2/sc-tagoptions.yaml'
      TimeoutInMinutes: 5
  tagassocenvprod:
    Type: AWS::ServiceCatalog::TagOptionAssociation
    Properties:
      TagOptionId: !GetAtt 'TagOptionsTemplate.Outputs.TagEnvironmentProd'
      ResourceId: !Ref 'WebserverProduct'
  tagassocenvdev:
    Type: AWS::ServiceCatalog::TagOptionAssociation
    Properties:
      TagOptionId: !GetAtt 'TagOptionsTemplate.Outputs.TagEnvironmentDev'
      ResourceId: !Ref 'WebserverProduct'
  tagassoccbdatainsights:
    Type: AWS::ServiceCatalog::TagOptionAssociation
    Properties:
      TagOptionId: !GetAtt 'TagOptionsTemplate.Outputs.TagChargeBackDataInsights'
      ResourceId: !Ref 'WebserverProduct'
  tagassoccbcbds:
    Type: AWS::ServiceCatalog::TagOptionAssociation
    Properties:
      TagOptionId: !GetAtt 'TagOptionsTemplate.Outputs.TagChargeBackDBs'
      ResourceId: !Ref 'WebserverProduct'
  tagassocccbacc:
    Type: AWS::ServiceCatalog::TagOptionAssociation
    Properties:
      TagOptionId: !GetAtt 'TagOptionsTemplate.Outputs.TagChargeBackAcc'
      ResourceId: !Ref 'WebserverProduct'
Outputs:
  ProductId:
    Value: !Ref 'WebserverProduct'
