AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Portfolio for Service Catalog. (fdp-1p4da46nc)
Parameters:
  PortfolioProvider:
    Type: String
    Description: Provider Name
    Default: IT Services
  PorfolioName:
    Type: String
    Description: Portfolio Name
    Default: Service Catalog EC2 Reference Architecture
  PorfolioDescription:
    Type: String
    Description: Portfolio Description
    Default: Service Catalog Portfolio that contains reference architecture products
      for Amazon Elastic Compute Cloud (EC2).
Resources:
  SCEC2portfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      ProviderName: !Ref 'PortfolioProvider'
      Description: !Ref 'PorfolioDescription'
      DisplayName: !Ref 'PorfolioName'
  LinkEndusersRole:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PrincipalARN: !ImportValue
        'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-RoleArn'
      PortfolioId: !Ref 'SCEC2portfolio'
      PrincipalType: IAM
  LinkEndusersGroup:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PrincipalARN: !ImportValue
        'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-GroupArn'
      PortfolioId: !Ref 'SCEC2portfolio'
      PrincipalType: IAM
Outputs:
  SCEC2portfolioId:
    Value: !Ref SCEC2portfolio
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-SCEC2portfolioId'
