AWSTemplateFormatVersion: '2010-09-09'
Description: Linux EC2 Webserver ServiceCatalog product. (fdp-1p4dlgcoi)
Parameters:
  PortfolioProvider:
    Type: String
    Description: Provider Name
  LaunchConstraintARN:
    Type: String
    Description: ARN of the launch constraint role for EC2 products.
  PortfolioId:
    Type: String
    Description: The SC portfolio this product will be attached to.
  RepoRootURL:
    Type: String
    Description: Root url for the repo containing the product templates.
  ProductVersionName:
    Type: String
    Description: The product version name in the service catalog
Resources:
  WebserverProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002
    Properties:
      Name: Amazon Elastic Compute Cloud (EC2) Linux Webserver
      Description: This product builds one Amazon Linux EC2 webserver (Apache or NGINX)
        instance.
      Owner: !Ref 'PortfolioProvider'
      Distributor: !Ref 'PortfolioProvider'
      ProvisioningArtifactParameters:
        - Description: NGINX webserver
          Info:
            LoadTemplateFromURL: !Sub '${RepoRootURL}ec2/sc-ec2-linux-nginx.yaml'
          Name: NGINX v2.0
        - Description: Apache webserver
          Info:
            LoadTemplateFromURL: !Sub '${RepoRootURL}ec2/sc-ec2-linux-apache.yaml'
          Name: !Ref 'ProductVersionName'
      'Fn::Transform':
        Name: 'AWS::Include'
        Parameters:
          Location : "s3://cfn-snippets-bucket-cloudformationsnippetsbucket-elu83sv8ocdz/scipoolprod-sc-lib-infra/support.yaml"
  Associatenginxcf:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref 'PortfolioId'
      ProductId: !Ref 'WebserverProduct'
  constraintnginxcf:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    DependsOn: Associatenginxcf
    Properties:
      PortfolioId: !Ref 'PortfolioId'
      ProductId: !Ref 'WebserverProduct'
      RoleArn: !Ref 'LaunchConstraintARN'
      Description: !Ref 'LaunchConstraintARN'
Outputs:
  ProductId:
    Value: !Ref 'WebserverProduct'
