AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Portfolio for Service Catalog. (fdp-1p5rtpgl6)
Parameters:
  PortfolioProvider:
    Type: String
    Description: Provider Name
    Default: IT Services
  PorfolioName:
    Type: String
    Description: Portfolio Name
    Default: Service Catalog S3 Reference Architecture
  PorfolioDescription:
    Type: String
    Description: Portfolio Description
    Default: Service Catalog Portfolio that contains reference architecture products
      for Amazon Simple Storage Service.
  RepoRootURL:
    Type: String
    Description: Root url for the repo containing the product templates.
    Default: https://s3.amazonaws.com/aws-service-catalog-reference-architectures/
  StackDatetime:
    Type: String
    Description: Last updated date and time of portfolio
    Default: ''
Resources:
  SCS3portfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      ProviderName: !Ref 'PortfolioProvider'
      Description: !Ref 'PorfolioDescription'
      DisplayName: !Ref 'PorfolioName'
  LinkEndusersRole:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PrincipalARN: !ImportValue
        'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-RoleArn'
      PortfolioId: !Ref 'SCS3portfolio'
      PrincipalType: IAM
  LinkEndusersGroup:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PrincipalARN: !ImportValue
        'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-GroupArn'
      PortfolioId: !Ref 'SCS3portfolio'
      PrincipalType: IAM
  s3privateEncproduct:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        PortfolioProvider: !Ref 'PortfolioProvider'
        LaunchConstraintARN: !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-s3-launchrole-LaunchRoleArn'
        PortfolioId: !Ref 'SCS3portfolio'
        RepoRootURL: !Ref 'RepoRootURL'
        StackDatetime: !Ref StackDatetime
      TemplateURL: !Sub '${RepoRootURL}s3/sc-product-s3-private-enc.yaml'
      TimeoutInMinutes: 5
  s3synapseproduct:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        PortfolioProvider: !Ref 'PortfolioProvider'
        LaunchConstraintARN: !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-s3-launchrole-LaunchRoleArn'
        PortfolioId: !Ref 'SCS3portfolio'
        RepoRootURL: !Ref 'RepoRootURL'
        StackDatetime: !Ref StackDatetime
      TemplateURL: !Sub '${RepoRootURL}s3/sc-product-s3-synapse.yaml'
      TimeoutInMinutes: 5

Outputs:
  SCS3portfolioId:
    Value: !Ref SCS3portfolio
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-SCS3portfolioId'
  s3privateEncproductId:
    Value: !GetAtt 's3privateEncproduct.Outputs.ProductId'
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-s3privateEncproductId'
  s3synapseproductId:
    Value: !GetAtt 's3synapseproduct.Outputs.ProductId'
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-s3synapseproductId'
