AWSTemplateFormatVersion: '2010-09-09'
Description: S3 private encrypted ServiceCatalog product. (fdp-1p4da46rq)
Parameters:
  PortfolioProvider:
    Type: String
    Description: Owner and Distributor Name
    Default: IT Services
  RepoRootURL:
    Type: String
    Description: Root url for the repo containing the product templates.
  StackDatetime:
    Type: String
    Description: Last updated date and time of portfolio
    Default: ''
Resources:
  scs3product:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002
    Properties:
      Name: S3 Private Encrypted Bucket
      Description: This product builds an AWS S3 bucket encrypted with private
        access accessible from any source.
      Owner: !Ref 'PortfolioProvider'
      Distributor: !Ref 'PortfolioProvider'
      ProvisioningArtifactParameters:
        - Description: !Sub 'Baseline version. Last portfolio update occurred at ${StackDatetime}.'
          Info:
            LoadTemplateFromURL: !Sub '${RepoRootURL}s3/sc-s3-encrypted-ra-v1.0.0.yaml'
          Name: v1.0.0
      'Fn::Transform':
        Name: 'AWS::Include'
        Parameters:
          Location : "s3://cfn-snippets-bucket-cloudformationsnippetsbucket-elu83sv8ocdz/scipoolprod-sc-lib-infra/support.yaml"
  Associates3:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !ImportValue
        'Fn::Sub': '${AWS::Region}-sc-portfolio-s3-basic-SCS3portfolioId'
      !Ref 'PortfolioId'
      ProductId: !Ref 'scs3product'
  constraintec2linux:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    DependsOn: Associates3
    Properties:
      PortfolioId: !ImportValue
        'Fn::Sub': '${AWS::Region}-sc-portfolio-s3-basic-SCS3portfolioId'
      ProductId: !Ref 'scs3product'
      RoleArn: !ImportValue
        'Fn::Sub': '${AWS::Region}-sc-s3-launchrole-LaunchRoleArn'
Outputs:
  ProductId:
    Value: !Ref 'scs3product'
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ProductId'