AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Portfolio for Service Catalog. (fdp-1p5rtpgl6)
Parameters:
  PortfolioProvider:
    Type: String
    Description: Provider Name
    Default: IT Services
  PorfolioName:
    Type: String
    Description: Portfolio Name
    Default: Service Catalog S3 Reference Architecture
  PorfolioDescription:
    Type: String
    Description: Portfolio Description
    Default: Service Catalog Portfolio that contains reference architecture products
      for Amazon Simple Storage Service.
Resources:
  SCS3portfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      ProviderName: !Ref 'PortfolioProvider'
      Description: !Ref 'PorfolioDescription'
      DisplayName: !Ref 'PorfolioName'
  LinkEndusersRole:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PrincipalARN: !ImportValue
        'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-RoleArn'
      PortfolioId: !Ref 'SCS3portfolio'
      PrincipalType: IAM
  LinkEndusersGroup:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PrincipalARN: !ImportValue
        'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-GroupArn'
      PortfolioId: !Ref 'SCS3portfolio'
      PrincipalType: IAM
Outputs:
  SCS3portfolioId:
    Value: !Ref SCS3portfolio
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-SCS3portfolioId'
