AWSTemplateFormatVersion: '2010-09-09'
Description: TaskCat testing template for all aws-service-catalog-reference-architectures
Parameters:
  PortfolioProvider:
    Type: String
    Description: Provider Name
    Default: IT Services
  PorfolioName:
    Type: String
    Description: Portfolio Name
    Default: Service Catalog EC2 Reference Architecture
  PorfolioDescription:
    Type: String
    Description: Portfolio Description
    Default: Service Catalog Portfolio that contains reference architecture products
      for Amazon Elastic Compute Cloud (EC2).
  LaunchRoleName:
    Type: String
    Description: Name of the launch constraint role for EC2 products. leave this blank
      to create the role.
  PrincipalRoleName1:
    Type: String
    Description: Name of the role that can execute products in this portfolio.
  LinkedRole1:
    Type: String
    Description: (Optional) The name of a role which can execute products in this
      portfolio.
    Default: ''
  LinkedRole2:
    Type: String
    Description: (Optional) The name of a second role which can execute products in
      this portfolio.
    Default: ''
  RepoRootURL:
    Type: String
    Description: Root url for the repo containing the product templates.
  ProductVersionName:
    Type: String
    Description: The product version name in the service catalog
Conditions:
  CreateLaunchConstraint: !Equals
    - !Ref 'LaunchRoleName'
    - ''
  CondLinkRole1: !Not
    - !Equals
      - !Ref 'LinkedRole1'
      - ''
  CondLinkRole2: !Not
    - !Equals
      - !Ref 'LinkedRole2'
      - ''
Resources:
  IAMenduser:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '${RepoRootURL}iam/sc-enduser-iam.yaml'
      TimeoutInMinutes: 5
  STACKec2portfolio:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMenduser
    Properties:
      Parameters:
        LaunchRoleName: ''
        PrincipalRoleName1: ''
        RepoRootURL: !Ref 'RepoRootURL'
      TemplateURL: !Sub '${RepoRootURL}ec2/sc-portfolio-ec2.yaml'
      TimeoutInMinutes: 5
  STACKs3portfolio:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - IAMenduser
    Properties:
      Parameters:
        LaunchRoleName: ''
        PrincipalRoleName1: ''
        RepoRootURL: !Ref 'RepoRootURL'
      TemplateURL: !Sub '${RepoRootURL}s3/sc-portfolio-s3-basic.yaml'
      TimeoutInMinutes: 5
