Description: "ServiceCatalog End User policy and group (fdp-1p4dlgcp7)"
Resources:
  SCEnduserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: ServiceCatalogEndusers
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSServiceCatalogEndUserFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSCloudTrailReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
        - !Ref SCEnduserExpandedPolicy
      Path: /
  SCEnduserRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ServiceCatalogEndusers
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSServiceCatalogEndUserFullAccess
        - !Ref SCEnduserExpandedPolicy
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - 'sts:AssumeRole'
  SCEnduserExpandedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Expand permissions SC users.
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - organizations:DescribeOrganization
              - servicecatalog:DescribeProvisionedProduct
            Resource: "*"
Outputs:
  EndUserGroupArn:
    Value: !GetAtt SCEnduserGroup.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-EndUserGroupArn'
  EndUserGroupName:
    Value: !Ref SCEnduserGroup
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-EndUserGroupName'
  EndUserRoleArn:
    Value: !GetAtt SCEnduserRole.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-EndUserRoleArn'
  EndUserRoleName:
    Value: !Ref SCEnduserRole
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-EndUserRoleName'
  EndUserExpandPolicy:
    Value: !Ref SCEnduserExpandedPolicy
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-SCEnduserExpandedPolicy'
